### PR TITLE
Library upgrade + AI system

### PR DESCRIPTION
**Pull request by TheMaverickProgrammer**
Please review this branch. It is a significant update that may affect the development environment. New DLLs and libs build find on my comp. I need another set of eyes to confirm that the new libs and external dependencies are working fine. 

Created AI and AI state management system. Rewrote shader pipeline which resolved the FPS bottleneck in the game. FPS sticks to 59-62 consistently.

### CODE REVIEW

**Comment by Pheelbert** [comment]
I'm out of town so i can't look much but nice work! When I come back I'll definetly look at that new AI stuff :).

**Comment by TheMaverickProgrammer** [comment]
I'd rather you take your time to look at it before merging in the future! You may want to rollback if there are issues with the libs and dependencies I built!

**Comment by Pheelbert** [comment]
After killing a mettaur, it came back and was in this state:
image

Whenever I start the game I get this message in console:
image

Also "finished move" debug logs are showed. Lastly, I moved once and got an assert but I didn't get a screenshot!

**Comment by TheMaverickProgrammer** [comment]
The mett delay death bug has something to do with the deleted flag or
animations. Look into LongExplosion artifact. I threw it together so its
probably not clean. The shader thing looks sfml related. Looks like the
glew extension didn't load or something was unsupported. What is your
setup? CPU? GPU?

The move assert is nee. Never had that. What was the message?

**Comment by Pheelbert** [comment]
Intel i7 7700K
GTX 960, I have latest drivers

As for the assert, we can ignore until we see it again aha

**Comment by TheMaverickProgrammer** [comment]
I've noticed sometimes sfml doesn't load resources. I'll start writing a
loading screen that retries failed resources.

**Comment by TheMaverickProgrammer** [comment]
That could be where the assert is coming from: if the anim didn't load and
animation component is trying to play empty frames.

**Comment by Pheelbert** [comment]
A loading screen is a great idea (y)!

**Pull request merged**
