### PR TITLE
More intuitive animation frame durations

### PR DESCRIPTION
**Pull request by Pheelbert**
@TheMaverickProgrammer Just a quick change. Let me know if you think that the relative duration thing was useful or not! I think that is isn't and the frames should all have equal durations relative to each other. By default, they are equal, otherwise you can specify it in the animations file. Let me know if you think that the animations look less realistic than before; if so, then you can revert those changes.

### CODE REVIEW

**Comment by TheMaverickProgrammer** [comment]
Will check soon. Some thoughts after reviewing code:

It makes more sense to calculate the total time duration by finding the sum of all the frames. Second it would allow some frames to **explicitly** set their own duration field if a particular frame needs to rest longer than others. For example:

```
# All frames default duration is "1.0" unless explicitly defined otherwise
animation state="MOB_ATTACKING" width="53" height="56"
frame startx="0" starty="0"
frame startx="53" starty="0"
frame startx="106" starty="0"
frame duration="1.5" startx="159" starty="0"
frame startx="212" starty="0"
frame startx="265" starty="0"
frame startx="318" starty="0"
frame startx="371" starty="0"
frame startx="424" starty="0" 
```

When loading the engine would add up +1.0 for 8 frames and +1.5 for 1 = 9.5 total animation duration. We could extend that by adding this following:

```
# All frames use the defined duration of "3.0"
animation state="MOB_ATTACKING" frameDuration="3.0" width="53" height="56"
frame startx="0" starty="0" # because animation is set to frameDuration = "3.0" this frame is "3.0"
frame startx="53" starty="0" # because animation is set to frameDuration = "3.0" this frame is "3.0"
...
```

I'm proposing these features because there is a need for setting individual frame duration's for some complex sprites. Especially sprites where enemies pause and can be countered.

**Comment by Pheelbert** [comment]
proof_of_work

I think this works! Let me know if you see any issues with it!

EDIT: I tried to keep the same duration that were already there, the float values there I found out by solving a simple system of equations so they should be good (they all add up to 0.8 as before).

**Comment by TheMaverickProgrammer** [comment]
It's a good start. Adding those explicit fields in the frame and in the animation would make this utility useful (and less typing!)

**Comment by TheMaverickProgrammer** [comment]
Update. Code works. I do think the frames look more crisp than before especially mob movement. We could probably afford slowing the animations down a hair even. Good work.

**Pull request merged**
